import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { RECORD_KINDS, recordKind } from '@paltas/shared'
import type { BusinessRecord, RecordKindDef } from '@paltas/shared'
import { api } from './client'

/**
 * Client access to the generic record store.
 *
 * Query keys are `records:<kind>`, which is exactly what the server broadcasts
 * after a write — so a change made in one tab invalidates the same key in every
 * other tab with no extra wiring here.
 */

export const recordsKey = (kind: string) => `records:${kind}`

export function useRecords<T = BusinessRecord>(kind: string) {
  return useQuery({
    queryKey: [recordsKey(kind)],
    queryFn: () => api.get<T[]>(`/records/${kind}`),
    // The registry is compiled in, so an unknown kind is a programming error
    // worth failing loudly on rather than a silent empty table.
    enabled: Boolean(RECORD_KINDS[kind]),
  })
}

export const kindDef = (kind: string): RecordKindDef => recordKind(kind)

/* -------------------------------------------------------------- mutations */

export function useCreateRecord(kind: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.post<BusinessRecord>(`/records/${kind}`, data),
    onSuccess: (created) => {
      // Append rather than refetch: the row is already authoritative, and this
      // keeps the new line visible the instant the dialog closes.
      qc.setQueryData<BusinessRecord[]>([recordsKey(kind)], (old) => (old ? [...old, created] : [created]))
      qc.invalidateQueries({ queryKey: ['activity'] })
      qc.invalidateQueries({ queryKey: ['metrics'] })
    },
  })
}

export function useUpdateRecord(kind: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: ({ id, ...data }: { id: string } & Record<string, unknown>) =>
      api.patch<BusinessRecord>(`/records/${kind}/${id}`, data),

    onMutate: async ({ id, ...data }) => {
      await qc.cancelQueries({ queryKey: [recordsKey(kind)] })
      const previous = qc.getQueryData<BusinessRecord[]>([recordsKey(kind)])
      qc.setQueryData<BusinessRecord[]>([recordsKey(kind)], (old) =>
        old?.map((r) => (r.id === id ? { ...r, ...data } : r)))
      return { previous }
    },
    onError: (_e, _v, ctx) => {
      if (ctx?.previous) qc.setQueryData([recordsKey(kind)], ctx.previous)
    },
    onSettled: () => {
      qc.invalidateQueries({ queryKey: [recordsKey(kind)] })
      qc.invalidateQueries({ queryKey: ['activity'] })
    },
  })
}

export function useDeleteRecord(kind: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) => api.del(`/records/${kind}/${id}`),
    onMutate: async (id) => {
      await qc.cancelQueries({ queryKey: [recordsKey(kind)] })
      const previous = qc.getQueryData<BusinessRecord[]>([recordsKey(kind)])
      qc.setQueryData<BusinessRecord[]>([recordsKey(kind)], (old) => old?.filter((r) => r.id !== id))
      return { previous }
    },
    onError: (_e, _v, ctx) => {
      if (ctx?.previous) qc.setQueryData([recordsKey(kind)], ctx.previous)
    },
    onSettled: () => {
      qc.invalidateQueries({ queryKey: [recordsKey(kind)] })
      qc.invalidateQueries({ queryKey: ['activity'] })
    },
  })
}

export interface ImportResult {
  imported: number
  rejected: Array<{ row: number; reason: string }>
  rows: BusinessRecord[]
}

export function useImportRecords(kind: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (csv: string) => api.post<ImportResult>(`/records/${kind}/import`, { csv }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: [recordsKey(kind)] })
      qc.invalidateQueries({ queryKey: ['activity'] })
    },
  })
}

/**
 * Downloads a kind as CSV. The file is generated by the server from the same
 * rows the table renders, so an export can never drift from the screen.
 */
export async function exportRecords(kind: string, label?: string): Promise<number> {
  const base = import.meta.env.VITE_API_URL ?? ''
  const res = await fetch(`${base}/api/records/${kind}/export.csv`)
  if (!res.ok) {
    const body = (await res.json().catch(() => null)) as { error?: string } | null
    throw new Error(body?.error ?? `Export failed (${res.status})`)
  }

  const blob = await res.blob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${(label ?? kind).toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${new Date().toISOString().slice(0, 10)}.csv`
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
  return blob.size
}

/** Reads a picked file as text, for the CSV import dialog. */
export function readFileAsText(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result ?? ''))
    reader.onerror = () => reject(new Error(`Could not read ${file.name}`))
    reader.readAsText(file)
  })
}

/**
 * Row count for a kind, for tab badges. Shares the list query's cache, so a tab
 * badge and the table below it can never disagree.
 */
export function useRecordCount(kind: string): number | undefined {
  return useRecords(kind).data?.length
}

/** Single-select within a kind — used by the subscription plan cards. */
export function useSelectRecord(kind: string, field: string) {
  const qc = useQueryClient()
  return useMutation({
    mutationFn: (id: string) => api.post<BusinessRecord[]>(`/records/${kind}/${id}/select`, { field }),
    onSuccess: (rows) => {
      qc.setQueryData([recordsKey(kind)], rows)
      qc.invalidateQueries({ queryKey: ['activity'] })
    },
  })
}
