import WebSocket from "ws";
const BASE = process.env.URL, LOCALE = process.env.LOCALE || "";
const host = new URL(BASE).hostname;
const targets = await (await fetch("http://127.0.0.1:9333/json/list")).json();
const ws = new WebSocket(targets.find(t=>t.type==="page").webSocketDebuggerUrl);
let id=0; const pend=new Map();
const send=(m,p={})=>new Promise((res,rej)=>{const i=++id;pend.set(i,{res,rej});ws.send(JSON.stringify({id:i,method:m,params:p}));});
await new Promise(r=>ws.on("open",r));
ws.on("message",d=>{const m=JSON.parse(d);if(m.id&&pend.has(m.id)){const{res,rej}=pend.get(m.id);pend.delete(m.id);m.error?rej(new Error(m.error.message)):res(m.result);}});
await send("Page.enable");await send("Runtime.enable");await send("Network.enable");
await send("Network.setCacheDisabled",{cacheDisabled:true});
if(LOCALE){await send("Network.setExtraHTTPHeaders",{headers:{"Accept-Language":LOCALE}});
  await send("Network.setCookie",{name:"paltas_locale",value:LOCALE,domain:host,path:"/"});}
await send("Page.navigate",{url:BASE});
await new Promise(r=>setTimeout(r,9000));
const ev=async e=>(await send("Runtime.evaluate",{expression:e,returnByValue:true})).result.value;
console.log("  lang/dir :", await ev("document.documentElement.lang+' / '+document.documentElement.dir"));
console.log("  rows     :", await ev("document.querySelectorAll('.d-row').length"));
console.log("  row names:", await ev("[...document.querySelectorAll('.d-row-head h2')].map(h=>h.textContent.trim()).join(' | ')||'(none)'"));
console.log("  cards    :", await ev("document.querySelectorAll('.d-card:not(.d-card-skeleton)').length"));
console.log("  empty    :", await ev("document.querySelector('.d-empty')?.textContent.trim().slice(0,70)||'(none)'"));
console.log("  demo?    :", await ev("/Serene|Palm Court Inn|Beachfront Family Villa|Ocean View Penthouse/.test(document.body.innerText)"));
ws.close();process.exit(0);
